version: "3.9"
services:
  restic-backup:
    image: restic/restic:latest
    restart: unless-stopped
    environment:
      - RESTIC_REPOSITORY=${RESTIC_REPOSITORY}
      - RESTIC_PASSWORD=${RESTIC_PASSWORD}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - RESTIC_PROGRESS_FPS=0.2
    volumes:
      - /srv:/backup:ro
      - ./backup.sh:/backup.sh:ro
    entrypoint: ["/bin/sh","/backup.sh"]
