---
version: "3.9"
services:
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./targets-audio.json:/etc/prometheus/targets/audio.json:ro
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    # Credentials are provided via monitoring.env
    env_file:
      - ./monitoring.env
    volumes:
      - grafana-data:/var/lib/grafana
  blackbox:
    image: prom/blackbox-exporter:latest
    restart: unless-stopped
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/config.yml:ro
volumes:
  grafana-data: {}
