version: "3.9"
services:
  camera-placeholder:
    image: alpine:3.20
    command: ["/bin/sh","-lc","sleep infinity"]
    restart: unless-stopped
    profiles: ["camera"]
    environment:
      - CAMERA_EXAMPLE_VAR=${CAMERA_EXAMPLE_VAR:-default}
    # Tolerant to missing camera; add device when present
    # devices:
    #   - "/dev/video0:/dev/video0"
