services:
  media-control:
    image: media-control:local
    build:
      context: ./control
      dockerfile: Dockerfile
    restart: unless-stopped
    network_mode: host
    ports:
      - "8082:8082"
    environment:
      MEDIA_CONTROL_TOKEN: ${MEDIA_CONTROL_TOKEN}
      HDMI_CONNECTOR: ${HDMI_CONNECTOR:-HDMI-A-1}
      HDMI_AUDIO_DEVICE: ${HDMI_AUDIO_DEVICE:-plughw:vc4hdmi,0}
    volumes:
      - /run:/run
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8082/healthz"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
