services:
  zigbee-mqtt:
    image: eclipse-mosquitto:2.0.20
    restart: unless-stopped
    network_mode: host
    environment:
      MOSQUITTO_USERNAME: ${ZIGBEE_MQTT_USER}
      MOSQUITTO_PASSWORD: ${ZIGBEE_MQTT_PASSWORD}
    volumes:
      - zigbee_mosquitto_data:/mosquitto/data
      - /opt/fleet/roles/hdmi-media/zigbee2mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    entrypoint:
      - /bin/sh
      - -c
      - >-
        set -e;
        if [ -n "$$MOSQUITTO_USERNAME" ] && [ -n "$$MOSQUITTO_PASSWORD" ]; then
          mosquitto_passwd -c -b /mosquitto/data/passwordfile "$$MOSQUITTO_USERNAME" "$$MOSQUITTO_PASSWORD";
        fi;
        exec /docker-entrypoint.sh mosquitto -c /mosquitto/config/mosquitto.conf
    healthcheck:
      test:
        - CMD-SHELL
        - >-
          if [ -n "$$MOSQUITTO_USERNAME" ]; then
            mosquitto_pub -h 127.0.0.1 -p 1883 -t healthcheck -m ok -u "$$MOSQUITTO_USERNAME" -P "$$MOSQUITTO_PASSWORD";
          else
            mosquitto_pub -h 127.0.0.1 -p 1883 -t healthcheck -m ok;
          fi
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:1.37.1
    restart: unless-stopped
    depends_on:
      zigbee-mqtt:
        condition: service_started
    privileged: true
    network_mode: host
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - zigbee2mqtt_data:/app/data
    environment:
      TZ: ${TZ:-UTC}
    healthcheck:
      test: ['CMD', 'wget', '--quiet', '--tries=1', '--spider', 'http://localhost:8084']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  zigbee_mosquitto_data: {}
  zigbee2mqtt_data: {}
