devices:
  - id: pi-audio-01
    name: 'Audio Player 01'
    role: audio-player
    kind: audio
    management:
      summary: 'Primary program audio feed (HiFiBerry)'
      host: pi-audio-01
    api:
      base_url: http://pi-audio-01:8081
      health_path: /healthz
      status_path: /status
      metrics_path: /metrics
      auth:
        type: bearer
        token_env: AUDIO_PI_AUDIO_01_TOKEN
    endpoints:
      - label: Control API
        url: http://pi-audio-01:8081
      - label: Health check
        url: http://pi-audio-01:8081/healthz
      - label: Prometheus metrics
        url: http://pi-audio-01:8081/metrics
      - label: Config
        url: http://pi-audio-01:8081/config
    monitoring:
      prometheus_targets:
        - job: audio-player
          target: pi-audio-01:8081
    operations:
      - id: health_check
        label: Run Health Check
        method: GET
        path: /healthz
        ui:
          type: button
          group: diagnostics
          result: text
      - id: status
        label: Pull Status
        method: GET
        path: /status
        ui:
          type: button
          group: diagnostics
          result: json
      - id: play_stream
        label: Play Stream
        method: POST
        path: /play
        body:
          source: stream
        ui:
          type: button
          group: control
      - id: play_file
        label: Play Fallback File
        method: POST
        path: /play
        body:
          source: file
        ui:
          type: button
          group: control
      - id: stop
        label: Stop Playback
        method: POST
        path: /stop
        ui:
          type: button
          group: control
      - id: config
        label: View Config
        method: GET
        path: /config
        ui:
          type: button
          group: diagnostics
          result: json
      - id: volume
        label: Set Volume
        method: POST
        path: /volume
        ui:
          type: slider
          group: control
          min: 0
          max: 2
          step: 0.05
          default: 1
          body_key: volume
  - id: pi-audio-02
    name: 'Audio Player 02'
    role: audio-player
    kind: audio
    management:
      summary: 'Secondary program audio feed (redundant playback)'
      host: pi-audio-02
    api:
      base_url: http://pi-audio-02:8081
      health_path: /healthz
      status_path: /status
      metrics_path: /metrics
      auth:
        type: bearer
        token_env: AUDIO_PI_AUDIO_02_TOKEN
    endpoints:
      - label: Control API
        url: http://pi-audio-02:8081
      - label: Health check
        url: http://pi-audio-02:8081/healthz
      - label: Prometheus metrics
        url: http://pi-audio-02:8081/metrics
      - label: Config
        url: http://pi-audio-02:8081/config
    monitoring:
      prometheus_targets:
        - job: audio-player
          target: pi-audio-02:8081
    operations:
      - id: health_check
        label: Run Health Check
        method: GET
        path: /healthz
        ui:
          type: button
          group: diagnostics
          result: text
      - id: status
        label: Pull Status
        method: GET
        path: /status
        ui:
          type: button
          group: diagnostics
          result: json
      - id: play_stream
        label: Play Stream
        method: POST
        path: /play
        body:
          source: stream
        ui:
          type: button
          group: control
      - id: play_file
        label: Play Fallback File
        method: POST
        path: /play
        body:
          source: file
        ui:
          type: button
          group: control
      - id: stop
        label: Stop Playback
        method: POST
        path: /stop
        ui:
          type: button
          group: control
      - id: config
        label: View Config
        method: GET
        path: /config
        ui:
          type: button
          group: diagnostics
          result: json
      - id: volume
        label: Set Volume
        method: POST
        path: /volume
        ui:
          type: slider
          group: control
          min: 0
          max: 2
          step: 0.05
          default: 1
          body_key: volume
  - id: pi-video-01
    name: 'Media Hub & Zigbee'
    role: hdmi-media
    kind: video
    management:
      summary: 'HDMI signage controller and Zigbee coordinator'
      host: pi-video-01
    api:
      base_url: http://pi-video-01:8082
      health_path: /healthz
      status_path: /status
      metrics_path: /metrics
      auth:
        type: bearer
        token_env: HDMI_PI_VIDEO_01_TOKEN
    endpoints:
      - label: Media control API
        url: http://pi-video-01:8082
      - label: Health check
        url: http://pi-video-01:8082/healthz
      - label: Prometheus metrics
        url: http://pi-video-01:8082/metrics
      - label: Zigbee2MQTT UI
        url: http://pi-video-01:8084
    monitoring:
      prometheus_targets:
        - job: media-control
          target: pi-video-01:8082
        - job: zigbee-coordinator
          target: pi-video-01:8082
    operations:
      - id: health_check
        label: Run Health Check
        method: GET
        path: /healthz
        ui:
          type: button
          group: diagnostics
          result: text
      - id: status
        label: Pull Status
        method: GET
        path: /status
        ui:
          type: button
          group: diagnostics
          result: json
      - id: video_power_on
        label: Power On Display
        method: POST
        path: /video/devices/pi-video-01/power
        body:
          power: on
        ui:
          type: button
          group: video
      - id: video_power_standby
        label: Enter Standby
        method: POST
        path: /video/devices/pi-video-01/power
        body:
          power: standby
        ui:
          type: button
          group: video
      - id: video_input_hdmi1
        label: Switch to HDMI 1
        method: POST
        path: /video/devices/pi-video-01/input
        body:
          input: HDMI1
        ui:
          type: button
          group: video
      - id: video_input_hdmi2
        label: Switch to HDMI 2
        method: POST
        path: /video/devices/pi-video-01/input
        body:
          input: HDMI2
        ui:
          type: button
          group: video
      - id: video_input_cast
        label: Switch to Chromecast
        method: POST
        path: /video/devices/pi-video-01/input
        body:
          input: CHROMECAST
        ui:
          type: button
          group: video
      - id: video_set_volume
        label: Set Output Volume
        method: POST
        path: /video/devices/pi-video-01/volume
        body:
          volumePercent: '{{volume}}'
        ui:
          type: slider
          group: video
          min: 0
          max: 100
          step: 5
          default: 40
          body_key: volumePercent
      - id: video_mute
        label: Mute Output
        method: POST
        path: /video/devices/pi-video-01/mute
        body:
          mute: true
        ui:
          type: button
          group: video
      - id: video_unmute
        label: Unmute Output
        method: POST
        path: /video/devices/pi-video-01/mute
        body:
          mute: false
        ui:
          type: button
          group: video
      - id: zigbee_pairing_start
        label: Open Zigbee Pairing Window
        method: POST
        path: /zigbee/pairing
        body:
          durationSeconds: 120
        ui:
          type: button
          group: zigbee
      - id: zigbee_pairing_stop
        label: Close Zigbee Pairing Window
        method: DELETE
        path: /zigbee/pairing
        ui:
          type: button
          group: zigbee
      - id: zigbee_refresh_devices
        label: Refresh Zigbee Devices
        method: GET
        path: /zigbee/devices
        ui:
          type: button
          group: zigbee
          result: json
  - id: pi-camera-01
    name: 'Camera'
    role: camera
    kind: camera
    management:
      summary: 'Primary video camera feeding MediaMTX'
      host: pi-camera-01
    api:
      base_url: http://pi-camera-01:8083
      health_path: /healthz
      status_path: /status
      metrics_path: /metrics
      auth:
        type: bearer
        token_env: CAMERA_PI_CAMERA_01_TOKEN
    endpoints:
      - label: Camera control API
        url: http://pi-camera-01:8083
      - label: Health check
        url: http://pi-camera-01:8083/healthz
      - label: Prometheus metrics
        url: http://pi-camera-01:8083/metrics
      - label: RTSP stream
        url: rtsp://pi-camera-01:8554/camera
      - label: HLS stream
        url: http://pi-camera-01:8888/camera/index.m3u8
    monitoring:
      prometheus_targets:
        - job: camera-control
          target: pi-camera-01:8083
    operations:
      - id: health_check
        label: Run Health Check
        method: GET
        path: /healthz
        ui:
          type: button
          group: diagnostics
          result: text
      - id: status
        label: Pull Status
        method: GET
        path: /status
        ui:
          type: button
          group: diagnostics
          result: json
      - id: probe_stream
        label: Probe Stream
        method: POST
        path: /probe
        ui:
          type: button
          group: diagnostics
          result: json
