server:
  http_listen_port: ${PROMTAIL_HTTP_PORT}
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: ${LOKI_ENDPOINT}
    batchwait: ${LOKI_BATCH_WAIT}
    batchsize: ${LOKI_BATCH_SIZE}
    backoff_config:
      min_period: ${LOKI_BACKOFF_MIN}
      max_period: ${LOKI_BACKOFF_MAX}
      max_retries: ${LOKI_BACKOFF_RETRIES}

scrape_configs:
  - job_name: system-journal
    journal:
      max_age: ${PROMTAIL_JOURNAL_MAX_AGE}
      labels:
        job: journal
        host: ${LOG_SOURCE_HOST}
        environment: ${LOG_ENVIRONMENT}
        site: ${LOG_SITE}
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
      - source_labels: ['__journal__hostname']
        target_label: 'journal_host'
      - source_labels: ['__journal__transport']
        target_label: 'transport'
      - source_labels: ['__journal_priority']
        target_label: 'priority'
      - source_labels: ['__journal__boot_id']
        target_label: 'boot_id'

  - job_name: docker-containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: ${PROMTAIL_DOCKER_REFRESH}
    relabel_configs:
      - source_labels: ['__meta_docker_container_id']
        target_label: 'container_id'
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container'
      - source_labels: ['__meta_docker_container_image']
        target_label: 'image'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: 'project'
      - replacement: ${LOG_SOURCE_HOST}
        target_label: host
      - replacement: ${LOG_ENVIRONMENT}
        target_label: environment
      - replacement: ${LOG_SITE}
        target_label: site
    pipeline_stages:
      - docker: {}
