server:
  http_listen_port: {{ env "PROMTAIL_HTTP_PORT" | default "9080" }}
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: {{ env "LOKI_ENDPOINT" | default "http://loki:3100/loki/api/v1/push" }}
    batchwait: {{ env "LOKI_BATCH_WAIT" | default "1s" }}
    batchsize: {{ env "LOKI_BATCH_SIZE" | default "102400" }}
    backoff_config:
      min_period: {{ env "LOKI_BACKOFF_MIN" | default "500ms" }}
      max_period: {{ env "LOKI_BACKOFF_MAX" | default "5s" }}
      max_retries: {{ env "LOKI_BACKOFF_RETRIES" | default "10" }}

scrape_configs:
  - job_name: system-journal
    journal:
      max_age: {{ env "PROMTAIL_JOURNAL_MAX_AGE" | default "12h" }}
      labels:
        job: journal
        host: {{ env "LOG_SOURCE_HOST" | default "unknown-host" }}
        environment: {{ env "LOG_ENVIRONMENT" | default "device" }}
        site: {{ env "LOG_SITE" | default "primary" }}
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
      - source_labels: ['__journal__hostname']
        target_label: 'journal_host'
      - source_labels: ['__journal__transport']
        target_label: 'transport'
      - source_labels: ['__journal_priority']
        target_label: 'priority'
      - source_labels: ['__journal__boot_id']
        target_label: 'boot_id'

  - job_name: docker-containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: {{ env "PROMTAIL_DOCKER_REFRESH" | default "5s" }}
    relabel_configs:
      - source_labels: ['__meta_docker_container_id']
        target_label: 'container_id'
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container'
      - source_labels: ['__meta_docker_container_image']
        target_label: 'image'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: 'project'
      - replacement: {{ env "LOG_SOURCE_HOST" | default "unknown-host" }}
        target_label: host
      - replacement: {{ env "LOG_ENVIRONMENT" | default "device" }}
        target_label: environment
      - replacement: {{ env "LOG_SITE" | default "primary" }}
        target_label: site
    pipeline_stages:
      - docker: {}
