services:
  icecast:
    build:
      context: ./docker
      dockerfile: icecast.Dockerfile
    restart: unless-stopped
    ports:
      - '8000:8000'
    environment:
      LOG_SERVICE: icecast
      LOG_ROLE: audio-player
      LOG_COMMIT: ${FLEET_LOG_COMMIT:-unknown}
    volumes:
      - icecast-data:/var/lib/icecast
      - icecast-log:/var/log/icecast2
    healthcheck:
      test: ['CMD-SHELL', 'wget -q --spider http://127.0.0.1:8000/status-json.xsl || exit 1']
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  icecast-data: {}
  icecast-log: {}
