---
version: "3.9"
services:
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro
      - ./targets-audio.json:/etc/prometheus/targets/audio.json:ro
      - ./targets-hdmi-media.json:/etc/prometheus/targets/hdmi-media.json:ro
      - ./targets-camera.json:/etc/prometheus/targets/camera.json:ro
    depends_on:
      - alertmanager
      - loki
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    # Credentials are provided via monitoring.env
    env_file:
      - ./monitoring.env
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ../../grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - loki
  loki:
    image: grafana/loki:2.9.1
    restart: unless-stopped
    command:
      - -config.file=/etc/loki/config.yml
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/config.yml:ro
      - loki-data:/loki
  blackbox:
    image: prom/blackbox-exporter:latest
    restart: unless-stopped
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/config.yml:ro
  alertmanager:
    image: prom/alertmanager:latest
    restart: unless-stopped
    ports:
      - "9093:9093"
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--storage.path=/alertmanager"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - ./secrets/slack-webhook.url:/etc/alertmanager/slack_webhook.url:ro
volumes:
  grafana-data: {}
  loki-data: {}
