---
version: '3.9'
services:
  promtail:
    image: grafana/promtail:2.9.3
    command: '-config.file=/etc/promtail/config.yml'
    restart: unless-stopped
    volumes:
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail-config.yml:/etc/promtail/config.yml:ro
