services:
  fleet-api:
    build: ../../apps/api
    image: ${FLEET_API_IMAGE:-ghcr.io/org/fleet-api:latest}
    env_file:
      - ../../vps/fleet.env
    ports:
      - '3005:3015'
    networks:
      - fleet-network
      - liquidsoap-network
    extra_hosts:
      - "pi-audio-01:100.127.65.25"
      - "pi-audio-02:100.122.210.53"
      - "pi-video-01:100.123.206.6"
      - "pi-camera-01:100.78.196.11"
    environment:
      - NODE_ENV=production
      - API_PORT=3015
      - DATABASE_URL=file:/data/fleet.db
      - SSE_HEARTBEAT_MS=15000
      - POLL_INTERVAL_MS=5000
      - LOKI_BASE_URL=http://vps-loki-1:3100
      - DEVICE_REGISTRY_PATH=/config/devices.json
      - LOG_SERVICE=fleet-api
      - LOG_ROLE=control-plane
      - LOG_COMMIT=${FLEET_LOG_COMMIT:-unknown}
      - PRISMA_QUERY_ENGINE_BINARY=/app/node_modules/.prisma/client/query-engine-linux-musl-arm64-openssl-3.0.x
    volumes:
      - fleet-data:/data
      - ./config:/config:ro
      - liquidsoap-music:/liquidsoap-music
    command: ['sh', '-c', 'npm run start']
    restart: unless-stopped

  fleet-worker:
    build: ../../apps/api
    image: ${FLEET_WORKER_IMAGE:-ghcr.io/org/fleet-api:latest}
    env_file:
      - ../../vps/fleet.env
    networks:
      - fleet-network
      - liquidsoap-network
    extra_hosts:
      - "pi-audio-01:100.127.65.25"
      - "pi-audio-02:100.122.210.53"
      - "pi-video-01:100.123.206.6"
      - "pi-camera-01:100.78.196.11"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/data/fleet.db
      - POLL_INTERVAL_MS=5000
      - DEVICE_REGISTRY_PATH=/config/devices.json
      - LOG_SERVICE=fleet-worker
      - LOG_ROLE=control-plane
      - LOG_COMMIT=${FLEET_LOG_COMMIT:-unknown}
      - PRISMA_QUERY_ENGINE_BINARY=/app/node_modules/.prisma/client/query-engine-linux-musl-arm64-openssl-3.0.x
    volumes:
      - fleet-data:/data
      - ./config:/config:ro
      - liquidsoap-music:/liquidsoap-music
    command: ['sh', '-c', 'npm run db:generate && npm run worker']
    healthcheck:
      disable: true
    restart: unless-stopped
    depends_on:
      - fleet-api

  fleet-ui:
    build: ../../apps/ui
    image: ${FLEET_UI_IMAGE:-fleet-console-local:latest}
    env_file:
      - ../../vps/fleet.env
    ports:
      - '3006:3000'
    networks:
      - fleet-network
    extra_hosts:
      - "pi-audio-01:100.127.65.25"
      - "pi-audio-02:100.122.210.53"
      - "pi-video-01:100.123.206.6"
      - "pi-camera-01:100.78.196.11"
    command: ['node', 'build']
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - ORIGIN=https://app.headspamartina.hr
      - API_BASE_URL=http://fleet-api:3015
      - VITE_API_BASE=/api
      - VITE_USE_MOCKS=0
      - VITE_FEATURE_CONSOLE=0
      - VITE_FEATURE_VIDEO=1
      - VITE_FEATURE_CAMERA=1
      - VITE_FEATURE_ZIGBEE=1
      - PUBLIC_API_URL=https://api.headspamartina.hr
      - NODE_OPTIONS="--max-old-space-size=2048"
    restart: unless-stopped
    depends_on:
      - fleet-api

  caddy:
    image: caddy:2
    ports: ['80:80', '443:443']
    networks:
      - fleet-network
    volumes:
      - ./caddy.fleet.Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - fleet-api
      - fleet-ui

networks:
  fleet-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-fleet
    external: false
  liquidsoap-network:
    external: true

volumes:
  fleet-data:
  caddy-data:
  caddy-config:
  liquidsoap-music:
    external: true
    name: vps_liquidsoap-music
