services:
  fleet-api:
    build: ../../apps/api
    image: ${FLEET_API_IMAGE:-ghcr.io/org/fleet-api:latest}
    env_file:
      - ../../vps/fleet.env
    ports:
      - "3005:3015"
    environment:
      - NODE_ENV=production
      - API_PORT=3015
      - DATABASE_URL=file:/data/fleet.db
      - SSE_HEARTBEAT_MS=15000
      - POLL_INTERVAL_MS=5000
      - DEVICE_YAML=/config/device-interfaces.yaml
      - DEVICE_REGISTRY_PATH=/config/device-interfaces.yaml
      - LOG_SERVICE=fleet-api
      - LOG_ROLE=control-plane
      - LOG_COMMIT=${FLEET_LOG_COMMIT:-unknown}
      - PRISMA_QUERY_ENGINE_BINARY=/app/node_modules/.prisma/client/query-engine-linux-musl-arm64-openssl-3.0.x
    volumes:
      - fleet-data:/data
      - ./config:/config:ro
    command: [ "sh", "-c", "npm run start" ]
    restart: unless-stopped

  fleet-worker:
    build: ../../apps/api
    image: ${FLEET_WORKER_IMAGE:-ghcr.io/org/fleet-api:latest}
    env_file:
      - ../../vps/fleet.env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/data/fleet.db
      - POLL_INTERVAL_MS=5000
      - DEVICE_REGISTRY_PATH=/config/device-interfaces.yaml
      - LOG_SERVICE=fleet-worker
      - LOG_ROLE=control-plane
      - LOG_COMMIT=${FLEET_LOG_COMMIT:-unknown}
      - PRISMA_QUERY_ENGINE_BINARY=/app/node_modules/.prisma/client/query-engine-linux-musl-arm64-openssl-3.0.x
    volumes:
      - fleet-data:/data
      - ./config:/config:ro
    command: [ "sh", "-c", "npm run db:generate && npm run worker" ]
    healthcheck:
      disable: true
    restart: unless-stopped
    depends_on:
      - fleet-api

  fleet-ui:
    build: ../../apps/ui
    image: ${FLEET_UI_IMAGE:-ghcr.io/org/fleet-ui:latest}
    env_file:
      - ../../vps/fleet.env
    ports:
      - "3006:3000"
    command: ["node", "build"]
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - ORIGIN=https://app.headspamartina.hr
      - FLEET_API_BASE=http://fleet-api:3015
      - VITE_API_BASE=/api
      - VITE_USE_MOCKS=0
      - PUBLIC_API_URL=https://app.headspamartina.hr/api
      - PUBLIC_API_BASE=/api
    restart: unless-stopped
    depends_on:
      - fleet-api

  caddy:
    image: caddy:2
    ports: ["80:80","443:443"]
    volumes:
      - ./caddy.fleet.Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - fleet-api
      - fleet-ui

volumes:
  fleet-data:
  caddy-data:
  caddy-config:
