services:
  netdata:
    image: netdata/netdata:v1.47.0
    hostname: ${HOSTNAME:-pi}
    restart: unless-stopped
    network_mode: host
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdata-data:/var/lib/netdata
      - netdata-cache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:19999/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

volumes:
  netdata-data: {}
  netdata-cache: {}

