name: CI Essentials

on:
  pull_request:

permissions:
  contents: read
  checks: write
  pull-requests: write

env:
  CI: true
  VITE_USE_MOCKS: '1'

jobs:
  typecheck:
    name: typecheck (node ${{ matrix.node }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20.x]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: |
            apps/api/package-lock.json
            apps/ui/package-lock.json
            package-lock.json

      - name: Install API dependencies
        working-directory: apps/api
        run: npm ci

      - name: Install UI dependencies
        working-directory: apps/ui
        run: npm ci

      - name: Typecheck API
        working-directory: apps/api
        run: npm run typecheck

      - name: Typecheck UI
        working-directory: apps/ui
        run: npm run typecheck

  build:
    name: build (node ${{ matrix.node }})
    runs-on: ubuntu-latest
    needs: typecheck
    strategy:
      matrix:
        node: [20.x]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: |
            apps/api/package-lock.json
            apps/ui/package-lock.json
            package-lock.json

      - name: Install API dependencies
        working-directory: apps/api
        run: npm ci

      - name: Install UI dependencies
        working-directory: apps/ui
        run: npm ci

      - name: Build API
        working-directory: apps/api
        run: |
          set -euo pipefail
          npm run build
          if [[ ! -d dist ]]; then
            echo "API build did not produce dist/" >&2
            exit 1
          fi

      - name: Build UI
        working-directory: apps/ui
        run: npm run build

  contract:
    name: contract validation (node ${{ matrix.node }})
    runs-on: ubuntu-latest
    needs: typecheck
    strategy:
      matrix:
        node: [20.x]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: |
            apps/api/package-lock.json
            apps/ui/package-lock.json
            package-lock.json

      - name: Install API dependencies
        working-directory: apps/api
        run: npm ci

      - name: Install UI dependencies
        working-directory: apps/ui
        run: npm ci

      - name: Ensure OpenAPI exists
        run: |
          if [ ! -f apps/api/openapi.yaml ]; then
            echo "OpenAPI spec not found at apps/api/openapi.yaml" >&2
            exit 1
          fi

      - name: Spectral lint
        working-directory: apps/api
        run: npm run contract

      - name: Generate UI client from OpenAPI
        working-directory: apps/ui
        run: npm run generate:openapi

      - name: Check generated client drift
        run: |
          git status --short
          git diff --stat
          git diff --exit-code -- apps/ui/src/lib/api/generated

  smoke:
    name: smoke verification (node ${{ matrix.node }})
    runs-on: ubuntu-latest
    needs: [build, contract]
    strategy:
      matrix:
        node: [20.x]
    env:
      API_BEARER: ci-test-bearer
      DEVICE_REGISTRY_JSON: '{"devices":[]}'
      API_HTTP_PORT: '3015'
      UI_HTTP_PORT: '4173'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: |
            apps/api/package-lock.json
            apps/ui/package-lock.json
            package-lock.json

      - name: Install API dependencies
        working-directory: apps/api
        run: npm ci

      - name: Install UI dependencies
        working-directory: apps/ui
        run: npm ci

      - name: Build API
        working-directory: apps/api
        run: npm run build

      - name: Build UI
        working-directory: apps/ui
        run: npm run build

      - name: Run smoke checks
        env:
          API_BEARER: ${{ env.API_BEARER }}
          DEVICE_REGISTRY_JSON: ${{ env.DEVICE_REGISTRY_JSON }}
          API_HTTP_PORT: ${{ env.API_HTTP_PORT }}
          UI_HTTP_PORT: ${{ env.UI_HTTP_PORT }}
          VITE_USE_MOCKS: '1'
        run: node ci/smoke/smoke.js

  lint:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20.x]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: |
            apps/api/package-lock.json
            apps/ui/package-lock.json
            package-lock.json

      - name: Install API dependencies
        working-directory: apps/api
        run: npm ci

      - name: Install UI dependencies
        working-directory: apps/ui
        run: npm ci

      - name: ESLint (API)
        working-directory: apps/api
        run: npm run lint

      - name: ESLint (UI)
        working-directory: apps/ui
        run: npm run lint

  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20.x]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: |
            apps/api/package-lock.json
            apps/ui/package-lock.json
            package-lock.json

      - name: Install API dependencies
        working-directory: apps/api
        run: npm ci

      - name: Install UI dependencies
        working-directory: apps/ui
        run: npm ci

      - name: Run API tests
        working-directory: apps/api
        run: |
          if node -e "const pkg=require('./package.json'); process.exit(pkg.scripts?.test ? 0 : 1)"; then
            npm test
          else
            echo "No API tests configured, skipping..."
          fi

      - name: Run UI tests
        working-directory: apps/ui
        run: |
          if node -e "const pkg=require('./package.json'); process.exit(pkg.scripts?.test ? 0 : 1)"; then
            npm test
          else
            echo "No UI tests configured, skipping..."
          fi
