name: Deploy to VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy services
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to VPS
        run: |
          echo "Starting deployment to VPS host"
          echo "Deployment logic handled via infrastructure automation"

  acceptance:
    name: Post-deploy acceptance
    needs: deploy
    runs-on: ubuntu-latest
    env:
      SSH_USER: ${{ secrets.VPS_SSH_USER }}
      AUDIOCTL_TOKEN: ${{ secrets.VPS_AUDIOCTL_TOKEN }}
      ICECAST_URL: ${{ secrets.VPS_ICECAST_URL }}
      ACCEPTANCE_AUDIO_ICECAST_URL: ${{ secrets.VPS_ICECAST_URL }}
      ACCEPTANCE_AUDIO_API: ${{ secrets.VPS_API_URL }}
      ACCEPTANCE_AUDIO_UI: ${{ secrets.VPS_UI_URL }}
      FLEET_API_BASE: ${{ secrets.VPS_API_URL }}
      FLEET_API_TOKEN: ${{ secrets.VPS_API_TOKEN }}
      FLEET_UI_BASE: ${{ secrets.VPS_UI_URL }}
      FLEET_UI_EXPECTED_TITLE: ${{ secrets.VPS_UI_EXPECTED_TITLE }}
      ACCEPTANCE_INSECURE: ${{ secrets.VPS_ACCEPTANCE_INSECURE }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure SSH key
        if: ${{ secrets.VPS_SSH_KEY != '' }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          cat <<'SSH' >> ~/.ssh/config
          Host *
            StrictHostKeyChecking no
            UserKnownHostsFile=/dev/null
          SSH

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Validate acceptance configuration
        run: |
          missing=()
          for key in FLEET_API_BASE FLEET_UI_BASE SSH_USER; do
            value=${!key:-}
            if [[ -z "$value" ]]; then
              missing+=("$key")
            fi
          done
          if (( ${#missing[@]} )); then
            echo "Missing required environment variables: ${missing[*]}" >&2
            exit 1
          fi

      - name: Install acceptance dependencies
        run: npm ci
        working-directory: tests/acceptance

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
        working-directory: tests/acceptance

      - name: Run acceptance suite
        run: npm run acceptance
        continue-on-error: true

      - name: Upload acceptance reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: acceptance-reports
          path: |
            reports/acceptance/

      - name: Publish JUnit report
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Acceptance Tests
          path: reports/acceptance/*.xml
          reporter: junit
          fail-on-error: false

      - name: Summarize acceptance results
        if: always()
        id: summarize
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const summaryPath = path.join(process.cwd(), 'reports', 'acceptance', 'summary.json');
            let summary = null;
            if (fs.existsSync(summaryPath)) {
              summary = JSON.parse(fs.readFileSync(summaryPath, 'utf8'));
            }
            const output = summary ? {
              status: summary.status,
              pass: summary.counts?.pass ?? 0,
              warn: summary.counts?.warn ?? 0,
              fail: summary.counts?.fail ?? 0,
            } : null;
            core.setOutput('summary', summary ? JSON.stringify(summary) : '');
            core.setOutput('status', output ? output.status : 'unknown');
            core.setOutput('pass', output ? output.pass : 0);
            core.setOutput('warn', output ? output.warn : 0);
            core.setOutput('fail', output ? output.fail : 0);
            if (summary) {
              await core.summary
                .addHeading('Acceptance summary')
                .addTable([
                  ['Status', 'Pass', 'Warn', 'Fail'],
                  [summary.status.toUpperCase(), String(output.pass), String(output.warn), String(output.fail)],
                ])
                .write();
            } else {
              await core.summary.addHeading('Acceptance summary').addRaw('No summary generated').write();
            }

      - name: Comment on PR with acceptance results
        if: ${{ github.event_name == 'pull_request' && always() }}
        uses: actions/github-script@v7
        with:
          summary: ${{ steps.summarize.outputs.summary }}
          script: |
            const summaryInput = core.getInput('summary');
            if (!summaryInput) {
              return;
            }
            const data = JSON.parse(summaryInput);
            const body = [
              '### Acceptance Suite',
              '',
              `Status: **${data.status.toUpperCase()}**`,
              `Pass: ${data.counts?.pass ?? 0} • Warn: ${data.counts?.warn ?? 0} • Fail: ${data.counts?.fail ?? 0}`,
            ].join('\n');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body,
            });

      - name: Ensure summary present
        if: ${{ steps.summarize.outputs.summary == '' }}
        run: |
          echo "Acceptance summary missing" >&2
          exit 2

      - name: Fail on acceptance warnings
        if: ${{ steps.summarize.outputs.status == 'warn' }}
        run: |
          echo "Acceptance finished with warnings" >&2
          exit 1

      - name: Fail on acceptance errors
        if: ${{ steps.summarize.outputs.status == 'fail' }}
        run: |
          echo "Acceptance failed" >&2
          exit 2
